runtime: python312
env: standard
instance_class: F1

entrypoint: gunicorn -b :$PORT --timeout 120 --workers 2 --threads 2 config.wsgi

handlers:
  - url: /static
    static_dir: staticfiles

  - url: /.*
    script: auto