# Generated by Django 6.0.3 on 2026-03-22 02:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('instructions', models.TextField()),
                ('default_sets', models.IntegerField(db_default=0)),
                ('default_reps', models.IntegerField(db_default=0)),
                ('default_weights', models.IntegerField(db_default=0)),
                ('default_duration', models.IntegerField(db_default=0)),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('email', models.CharField(max_length=80, validators=[django.core.validators.EmailValidator()])),
                ('contact_no', models.CharField(max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'trainers',
            },
        ),
        migrations.CreateModel(
            name='TagExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises_tags', to='orm.exercise')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_exercises', to='orm.tag')),
            ],
            options={
                'db_table': 'tags_exercises',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='orm.trainer'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='orm.trainer'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(5)])),
                ('age', models.IntegerField(db_default=0, validators=[django.core.validators.MinValueValidator(18)])),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.EmailValidator()])),
                ('contact_no', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10)])),
                ('goals', models.TextField()),
                ('preferred_times', models.CharField(max_length=200)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='orm.trainer')),
            ],
            options={
                'db_table': 'clients',
                'unique_together': {('trainer', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('trainer_review_notes', models.TextField()),
                ('client_remarks', models.TextField()),
                ('is_completed', models.BooleanField(db_default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='orm.client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='orm.trainer')),
            ],
            options={
                'db_table': 'workouts',
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('actual_sets', models.IntegerField()),
                ('actual_reps', models.IntegerField()),
                ('actual_weight', models.IntegerField()),
                ('actual_duration', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_workout_exercise', to='orm.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='orm.workout')),
            ],
            options={
                'db_table': 'workouts_exercises',
            },
        ),
    ]
