# Generated by Django 6.0.3 on 2026-03-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
