# Generated by Django 6.0.3 on 2026-03-22 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='actual_duration',
            field=models.IntegerField(db_default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='actual_reps',
            field=models.IntegerField(db_default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='actual_sets',
            field=models.IntegerField(db_default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='actual_weight',
            field=models.IntegerField(db_default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='duration',
            field=models.IntegerField(db_default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.IntegerField(db_default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.IntegerField(db_default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='weight',
            field=models.IntegerField(db_default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
