# Generated by Django 6.0.3 on 2026-03-22 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_alter_workoutexercise_actual_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=25)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clients_info', to='orm.client')),
            ],
            options={
                'db_table': 'clients_info',
            },
        ),
    ]
