# Generated by Django 6.0.3 on 2026-03-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_trainer_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
