"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kdu+gvenhn8d3ayyg2g@vaxcmil@4grxy6cv%2rewq)@4)t+_e'

from .info import G_API_KEY, OR_API_KEY, U_GPT_KEY
GEMINI_API_KEY = G_API_KEY
OPENROUTER_API_KEY = OR_API_KEY
UNI_CHATGPT_KEY = U_GPT_KEY
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

STATIC_URL = "/static/"

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# application messages
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'orm',
    'trainer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

from .info import DB_ENGINE, DB_NAME, DB_USER, DB_PWD, DB_HOST, DB_PORT
DATABASES = {
    'default': {
        'ENGINE'    : DB_ENGINE,
        'NAME'      : DB_NAME,
        'USER'      : DB_USER,
        'PASSWORD'  : DB_PWD,
        'HOST'      : DB_HOST,
        'PORT'      : DB_PORT
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators


# LOGIN_URL = 'login' 
# LOGIN_REDIRECT_URL = 'home'
# LOGOUT_REDIRECT_URL = 'index'

# using path names
LOGIN_URL = 'login' # These go by the ****name**** in urls.py, NOT the URL String/Param

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'index'

# customized User with is_trainer indicator
AUTH_USER_MODEL = "orm.UserTrainer"
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# This is for social-auth login
# =================================== SOCIAL LOGINS =========================================== #
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.github.GithubOAuth2',
    'django.contrib.auth.backends.ModelBackend',  # Keep for username/password login
)

from .info import S_AUTH_GOOGLE_K, S_AUTH_GOOGLE_S
# Google OAuth2
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = S_AUTH_GOOGLE_K
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = S_AUTH_GOOGLE_S
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]

# Github OAuth2
# SOCIAL_AUTH_GITHUB_KEY = "123"
# SOCIAL_AUTH_GITHUB_SECRET = "123"
# SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']           # make sureto get email



SOCIAL_AUTH_RAISE_EXCEPTIONS = True
SOCIAL_AUTH_LOGIN_ERROR_URL = 'login'

# 3. CRITICAL: Add this to clear the partial session on failure
SOCIAL_AUTH_CLEAN_USER_KEEP_SESSION = True
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'prompt': 'select_account'
}

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.social_auth.associate_by_email',  # Finds your record
    'social_core.pipeline.social_auth.associate_user',      # <--- THE MISSING LINK
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 1. The URL used to access static files in the browser
STATIC_URL = 'static/'
# 2. Where Django LOOKS for your files during development (Crucial!)
# This matches your project/static/ folder
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# 3. Where Django COPIES files for production (Ignore this for now)
# We name it 'staticfiles' to avoid a name conflict with your source folder
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')